const CHANNELS = [
  {
    id: 0,
    label: 'S',
    color: 'black',
    disabled: true,
    current_id: -1,
    rgbColor: [255, 255, 255],
    channelsVisible: false,
  },
  {
    id: 1,
    label: 'B',
    color: 'blue',
    disabled: true,
    current_id: -1,
    rgbColor: [0, 0, 255],
    channelsVisible: false,
  },
  {
    id: 2,
    label: 'G',
    color: 'green',
    disabled: true,
    current_id: -1,
    rgbColor: [0, 255, 0],
    channelsVisible: false,
  },
  {
    id: 3,
    label: 'R',
    color: 'red',
    disabled: true,
    current_id: -1,
    rgbColor: [255, 0, 0],
    channelsVisible: false,
  },
  {
    id: 4,
    label: 'C',
    color: 'cyan',
    disabled: true,
    current_id: -1,
    rgbColor: [0, 255, 255],
    channelsVisible: false,
  },
  {
    id: 5,
    label: 'Y',
    color: 'yellow',
    disabled: true,
    current_id: -1,
    rgbColor: [255, 255, 0],
    channelsVisible: false,
  },
  {
    id: 6,
    label: 'M',
    color: 'magenta',
    disabled: true,
    current_id: -1,
    rgbColor: [255, 0, 255],
    channelsVisible: false,
  },
];

export default CHANNELS;
